[[deqp]]
deqp = "/deqp-gl/external/openglcts/modules/glcts"
caselists = [
    "/deqp-gl/mustpass/gl46-main.txt",
    "/deqp-gl/mustpass/gl46-khr-single.txt",
]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 180.0
renderer_check = "zink.*llvmpipe"
