# Basic test set
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
timeout = 300
renderer_check = "Turnip Adreno .* 630"
tests_per_group = 5000

# force-gmem testing
# Autotuner forces sysmem on most CTS tests
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
timeout = 300
prefix = "gmem-"
fraction = 10
tests_per_group = 5000
[deqp.env]
TU_DEBUG = "gmem,forcebin"

# force-sysmem testing
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
timeout = 300
include = ["dEQP-VK.renderpass.*"]
prefix = "bypass-"
tests_per_group = 5000
[deqp.env]
TU_DEBUG = "sysmem"
