# Basic test set
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
renderer_check = "Turnip Adreno .* 660"
tests_per_group = 5000

# force-gmem testing
# Autotuner forces sysmem on most CTS tests
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
prefix = "gmem-"
fraction = 20
tests_per_group = 5000
[deqp.env]
TU_DEBUG = "gmem,forcebin"

# spillall and stale regs testing disabled due to crashing a ton.
#[[deqp]]
#deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
#caselists = ["/deqp-vk/mustpass/vk-main.txt"]
#skips = ["install/freedreno-a6xx-skips.txt"]
#include = ["dEQP-VK.graphicsfuzz.*", "dEQP-VK.subgroups.ballot*"]
#prefix = "spill-"
#tests_per_group = 2000
#[deqp.env]
#IR3_SHADER_DEBUG = "spillall"

# testing for stale regs usage
#[[deqp]]
#deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
#caselists = ["/deqp-vk/mustpass/vk-main.txt"]
#skips = ["install/freedreno-a6xx-skips.txt"]
#prefix = "stale-regs-"
#fraction = 200
#tests_per_group = 5000
#[deqp.env]
#TU_DEBUG = "gmem,forcebin"
#TU_DEBUG_STALE_REGS_RANGE = "0x0c00,0xbe01"
#TU_DEBUG_STALE_REGS_FLAGS = "cmdbuf,renderpass"
