# Basic test set
[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt", "install/freedreno-a750-premerge-skips.txt"]
renderer_check = "Turnip Adreno .* 750"
tests_per_group = 10000

# force-gmem testing
# Autotuner forces sysmem on most CTS tests
[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt", "install/freedreno-a750-premerge-skips.txt"]
prefix = "gmem-"
fraction = 20
tests_per_group = 1000
[deqp.env]
TU_DEBUG = "gmem,forcebin"

# force-gmem with unaligned gmem store testing
[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt", "install/freedreno-a750-premerge-skips.txt"]
include = ["dEQP-VK.renderpass.*"]
prefix = "gmem-unaligned-"
fraction = 10
tests_per_group = 1000
[deqp.env]
TU_DEBUG = "gmem,unaligned_store"

# force-sysmem testing
[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt", "install/freedreno-a750-premerge-skips.txt"]
include = ["dEQP-VK.renderpass.*"]
prefix = "bypass-"
fraction = 10
tests_per_group = 1000
[deqp.env]
TU_DEBUG = "sysmem"

# force-spilling testing
# NOTE: Disabled due to crashing the board so hard it goes into Sahara mode
# [[deqp]]
# deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
# caselists = ["/deqp/mustpass/vk-main.txt"]
# skips = ["install/freedreno-a6xx-skips.txt", "install/freedreno-a750-premerge-skips.txt"]
# include = ["dEQP-VK.graphicsfuzz.*"]
# prefix = "spill-"
# fraction = 10
# tests_per_group = 1000
# [deqp.env]
# IR3_SHADER_DEBUG = "spillall"

# dynamic rendering testing using emulated renderpass
[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt", "install/freedreno-a750-premerge-skips.txt"]
include = ["dEQP-VK.renderpass2.*"]
prefix = "dynamic-"
tests_per_group = 10000
[deqp.env]
TU_DEBUG = "dynamic"

# testing for stale regs usage
# NOTE: Disabled due to constant gpu hangs
# [[deqp]]
# deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
# caselists = ["/deqp/mustpass/vk-main.txt"]
# skips = ["install/freedreno-a6xx-skips.txt", "install/freedreno-a750-premerge-skips.txt"]
# prefix = "stale-regs-"
# fraction = 100
# tests_per_group = 1000
# [deqp.env]
# TU_DEBUG = "gmem,forcebin"
# TU_DEBUG_STALE_REGS_RANGE = "0x0c00,0xbe01"
# TU_DEBUG_STALE_REGS_FLAGS = "cmdbuf,renderpass"
# FREEDRENO_HANGCHECK_MS = "2000"
