# Basic test set
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
fraction = 40
renderer_check = "Turnip Adreno .* 630"
tests_per_group = 5000

# force-gmem testing (~1 min)
# Autotuner forces sysmem on most CTS tests
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
prefix = "gmem-"
fraction = 100
tests_per_group = 5000
[deqp.env]
TU_DEBUG = "gmem,forcebin"

# force-gmem with unaligned gmem store testing (~15s)
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
include = ["dEQP-VK.renderpass.*"]
prefix = "gmem-unaligned-"
fraction = 5
tests_per_group = 5000
[deqp.env]
TU_DEBUG = "gmem,unaligned_store"

# force-sysmem testing (~15s)
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
include = ["dEQP-VK.renderpass.*"]
prefix = "bypass-"
fraction = 15
tests_per_group = 5000
[deqp.env]
TU_DEBUG = "sysmem"

# force-spilling testing (~10s)
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
include = ["dEQP-VK.graphicsfuzz.*"]
prefix = "spill-"
fraction = 5
tests_per_group = 1000
[deqp.env]
# Increase the hangcheck timer for our spilling tests which bump up against
# the .5s default.
FREEDRENO_HANGCHECK_MS = "2000"
IR3_SHADER_DEBUG = "spillall"

# dynamic rendering testing using emulated renderpass
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
include = ["dEQP-VK.renderpass2.*"]
prefix = "dynamic-"
fraction = 5
tests_per_group = 5000
[deqp.env]
TU_DEBUG = "dynamic"

# testing for stale regs usage
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
prefix = "stale-regs-"
fraction = 100
tests_per_group = 5000
[deqp.env]
TU_DEBUG = "gmem,forcebin"
TU_DEBUG_STALE_REGS_RANGE = "0x0c00,0xbe01"
TU_DEBUG_STALE_REGS_FLAGS = "cmdbuf,renderpass"
