# Basic test set
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
renderer_check = "Turnip Adreno .* 618"
fraction = 2
tests_per_group = 5000

# force-gmem testing
# Autotuner forces sysmem on most CTS tests
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
prefix = "gmem-"
fraction = 15
tests_per_group = 5000
[deqp.env]
TU_DEBUG = "gmem,forcebin"

[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
include = ["dEQP-VK.graphicsfuzz.*", "dEQP-VK.subgroups.ballot*"]
prefix = "spill-"
tests_per_group = 2000
[deqp.env]
IR3_SHADER_DEBUG = "spillall"
