[[deqp]]
deqp = "/deqp/modules/gles2/deqp-gles2"
caselists = ["/deqp/mustpass/gles2-main.txt"]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
version_check = "GL ES 3.2.*git"
renderer_check = "llvmpipe"

[[deqp]]
deqp = "/deqp/modules/gles3/deqp-gles3"
caselists = ["/deqp/mustpass/gles3-main.txt"]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]

[[deqp]]
deqp = "/deqp/modules/gles31/deqp-gles31"
caselists = ["/deqp/mustpass/gles31-main.txt"]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
  [deqp.env]
  # Stress test NIR clone/serialization for GLES3.1 (which should cover most of the featureset).
  # Costs about 30% extra runtime.
  NIR_DEBUG="clone,serialize"

[[deqp]]
deqp = "/deqp/external/openglcts/modules/glcts"
caselists = [
    "/deqp/mustpass/gles2-khr-main.txt",
    "/deqp/mustpass/gles3-khr-main.txt",
    "/deqp/mustpass/gles31-khr-main.txt",
]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]

# Note that KHR-GL3* test sets include all tests from the previous
# version, so we only need to run one test list (unlike dEQP-GLES,
# where the test sets are separate).
[[deqp]]
deqp = "/deqp/external/openglcts/modules/glcts"
caselists = [
    "/deqp/mustpass/gl45-main.txt",
    "/deqp/mustpass/gl45-khr-single.txt",
]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]

[[deqp]]
deqp = "/deqp/modules/egl/deqp-egl-x11"
caselists = ["/deqp/mustpass/egl-main.txt"]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]

[[deqp]]
deqp = "/deqp/modules/egl/deqp-egl-wayland"
caselists = ["/deqp/mustpass/egl-main.txt"]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
prefix = "wayland-"

[[piglit]]
piglit_folder = "/piglit"
profile = "quick"
process_isolation = true
  [piglit.env]
  # workaround for spec@arb_shader_texture_lod@execution@arb_shader_texture_lod-texgradcube
  GALLIVM_PERF = "no_quad_lod"
