# Basic test set
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
fraction = 6
renderer_check = "ADL"
tests_per_group = 5000

# Rerun query tests with shader query optimizations (14443 tests)
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
renderer_check = "ADL"
include = ["dEQP-VK.query_pool.*"]
prefix = "shaderquery-"
tests_per_group = 5000
[deqp.env]
  query_clear_with_blorp_threshold = "0"
  query_copy_with_shader_threshold = "0"

# Rerun indirect tests with in-place generation shader optimizations
# (3814 tests)
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
renderer_check = "ADL"
include = ["dEQP-VK.draw.*indirect*"]
prefix = "indirectgen-inplace-"
tests_per_group = 5000
[deqp.env]
  generated_indirect_threshold = "0"

# Rerun indirect tests with ring-buffer generation shader optimizations
# (3814 tests)
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
renderer_check = "ADL GT2"
include = ["dEQP-VK.draw.*indirect*"]
prefix = "indirectgen-inring-"
tests_per_group = 5000
[deqp.env]
  generated_indirect_threshold = "0"
  generated_indirect_ring_threshold = "0"

