# Basic test set
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
skips = ["install/anv-tgl-skips.txt"]
renderer_check = "TGL GT2"
tests_per_group = 5000
