include:
  - local: 'src/intel/ci/gitlab-ci-inc.yml'

anv-jsl-vk:
  extends:
    - .anv-test
    - .lava-acer-cb317-1h-c3z6-dedede:x86_64
  variables:
    DEQP_SUITE: anv-jsl
    VK_DRIVER: intel
    # force fixed kernel, since too many flakes and unexpected results seen with 6.13-rc4 and 6.11-rc7
    EXTERNAL_KERNEL_TAG: "v6.6.21-mesa-f8ea"
  parallel: 5

anv-jsl-vk-full:
  extends:
    - anv-jsl-vk
    - .anv-manual-rules
  variables:
    DEQP_SUITE: anv-jsl-full
  parallel: 4
  timeout: 2h

anv-adl-vk:
  extends:
    - .anv-test
    - .lava-acer-cbv514-1h-34uz-brya:x86_64
  variables:
    DEQP_SUITE: anv-adl
    VK_DRIVER: intel
  timeout: 30m
  parallel: 4

anv-adl-vk-full:
  extends:
    - anv-adl-vk
    - .anv-manual-rules
  variables:
    DEQP_SUITE: anv-adl-full
  timeout: 1h 40m
  parallel: 3

anv-tgl-vk:
  extends:
    - .anv-test
    - .lava-acer-cp514-2h-1160g7-volteer:x86_64
  variables:
    DEQP_SUITE: anv-tgl
    VK_DRIVER: intel
  parallel: 5  # 5 - 5 # -1 for zink, but it's disabled now

anv-tgl-vk-full:
  extends:
    - anv-tgl-vk
    - .anv-manual-rules
  variables:
    DEQP_SUITE: anv-tgl-full
  timeout: 100m
  parallel: 4

# Takes too long since the 1.3.7.0 CTS uprev.
.hasvk-hsw-full:
  extends:
    - .anholt-hsw-test
    - .test-vk
    - .deqp-test
    - .hasvk-manual-rules
  variables:
    GPU_VERSION: hasvk-hsw
    DEQP_SUITE: hasvk-hsw
    VK_DRIVER: intel_hasvk
    MESA_VK_IGNORE_CONFORMANCE_WARNING: 1
  timeout: 2h

hasvk-hsw:
  extends:
    - .hasvk-hsw-full
  variables:
    DEQP_FRACTION: 10

anv-jsl-angle:
  extends:
    - .anv-angle-test
    - .lava-acer-cb317-1h-c3z6-dedede:x86_64
  variables:
    DEQP_SUITE: anv-jsl-angle
    GPU_VERSION: angle-anv-jsl

anv-jsl-angle-full:
  extends:
    - anv-jsl-angle
    - .anv-manual-rules
  variables:
    DEQP_SUITE: anv-jsl-angle-full
  parallel: 2

anv-adl-angle:
  extends:
    - .anv-angle-test
    - .lava-acer-chromebox-cxi5-brask:x86_64
  variables:
    DEQP_SUITE: anv-adl-angle
    GPU_VERSION: angle-anv-adl
  timeout: 30m
  parallel: 4

anv-adl-angle-full:
  extends:
    - anv-adl-angle
    - .anv-manual-rules
  variables:
    DEQP_SUITE: anv-adl-angle-full
  timeout: 30m

anv-tgl-angle:
  extends:
    - .anv-angle-test
    - .lava-acer-cp514-2h-1130g7-volteer:x86_64
  variables:
    DEQP_SUITE: anv-tgl-angle
    GPU_VERSION: angle-anv-tgl
  parallel: 2

anv-tgl-angle-full:
  extends:
    - anv-tgl-angle
    - .anv-manual-rules
  variables:
    DEQP_SUITE: anv-tgl-angle-full
  parallel: null

iris-apl-deqp:
  extends:
    - .iris-apl-test
    - .iris-manual-rules
  variables:
    DEQP_SUITE: iris-apl
  parallel: 3

iris-apl-egl:
  extends:
    - .iris-apl-test
  variables:
    PIGLIT_NO_WINDOW: 0
    HWCI_START_XORG: 1
    HWCI_START_WESTON: 1
    DEQP_SUITE: iris-apl-egl

iris-glk-deqp:
  extends:
    - .iris-glk-test
  variables:
    DEQP_SUITE: iris-glk

iris-glk-egl:
  extends:
    - .iris-glk-test
  variables:
    PIGLIT_NO_WINDOW: 0
    HWCI_START_XORG: 1
    HWCI_START_WESTON: 1
    DEQP_SUITE: iris-glk-egl

iris-amly-deqp:
  extends:
    - .iris-amly-test
  variables:
    DEQP_SUITE: iris-amly
  parallel: 3

iris-kbl-deqp:
  extends:
    - .iris-kbl-test
  variables:
    DEQP_SUITE: iris-kbl
  parallel: 3

iris-cml-deqp:
  extends:
    - .iris-cml-test
    # moved to nightly because of networking issues, gpu tests are all passing as expected
    - .iris-manual-rules
  variables:
    DEQP_SUITE: iris-cml
  parallel: 8

iris-jsl-deqp:
  extends:
    - .iris-test
    - .lava-acer-cb317-1h-c3z6-dedede:x86_64
  variables:
    DEQP_SUITE: iris-jsl
    GPU_VERSION: iris-jsl
    DEQP_FRACTION: 8
  parallel: 2

iris-amly-egl:
  extends:
    - .iris-amly-test
  variables:
    PIGLIT_NO_WINDOW: 0
    HWCI_START_XORG: 1
    HWCI_START_WESTON: 1
    DEQP_SUITE: iris-amly-egl

iris-kbl-piglit:
  extends:
    - .iris-kbl-test
    - .lava-piglit
  parallel: 2
  variables:
    HWCI_START_XORG: 1
    PIGLIT_NO_WINDOW: 0
    PIGLIT_PLATFORM: mixed_glx_egl
    PIGLIT_PROFILES: gpu

iris-apl-traces:
  variables:
    GPU_VERSION: intel-apl
  extends:
    - .iris-apl-test
    - .iris-traces

iris-glk-traces:
  variables:
    GPU_VERSION: intel-glk
  extends:
    - .iris-glk-test
    - .iris-traces

iris-amly-traces:
  variables:
    GPU_VERSION: intel-amly
  extends:
    - .iris-amly-test
    - .iris-traces

iris-kbl-traces:
  variables:
    GPU_VERSION: intel-kbl
  extends:
    - .iris-kbl-test
    - .iris-traces

iris-cml-traces:
  variables:
    GPU_VERSION: intel-cml
  extends:
    - .iris-cml-test
    - .iris-traces
    # moved to nightly because of networking issues, gpu tests are all passing as expected
    - .iris-manual-rules

iris-apl-traces-performance:
  extends:
    - .iris-apl-test
    - .profile-traces
  variables:
    GPU_VERSION: intel-apl

iris-glk-traces-performance:
  extends:
    - .iris-glk-test
    - .profile-traces
  variables:
    GPU_VERSION: intel-glk

iris-amly-traces-performance:
  extends:
    - .iris-amly-test
    - .profile-traces
  variables:
    GPU_VERSION: intel-amly

iris-kbl-traces-performance:
  extends:
    - .iris-kbl-test
    - .profile-traces
  variables:
    GPU_VERSION: intel-kbl

intel-adl-cl:
  extends:
    - .intel-adl-test
    - .lava-acer-n20q11-r856ltn-p1s2-nissa:x86_64
    - .intel-rules
  rules:
    - !reference [.intel-adl-test, rules]
    - !reference [.intel-rules, rules]
    - !reference [.rusticl-rules, rules]
  variables:
    DEQP_SUITE: intel-adl-cl
    GPU_VERSION: intel-adl
    VK_DRIVER: intel
    HWCI_START_WESTON: 1
  timeout: 20m
  parallel: 2

intel-adl-skqp:
  extends:
    - .intel-adl-test
    - .lava-acer-n20q11-r856ltn-p1s2-nissa:x86_64
  variables:
    DEQP_SUITE: intel-adl-skqp
    VK_DRIVER: intel
    HWCI_START_XORG: 1
  timeout: 30m

intel-tgl-skqp:
  extends:
    - .intel-tgl-test
    - .lava-acer-cp514-2h-1130g7-volteer:x86_64
  variables:
    DEQP_SUITE: intel-tgl-skqp
    VK_DRIVER: intel
    HWCI_START_XORG: 1
