include:
  - local: 'src/intel/ci/gitlab-ci-inc.yml'

# Manual test rules for using g33 in ondracka r300 farm.
.ondracka-g33-test:
  extends:
    - .b2c-x86_64-test-gl-manual # use debian-build-testing rather than debian-testing
    - .i915g-manual-rules
  variables:
    FDO_CI_CONCURRENT: 2
    GPU_VERSION: i915-g33
    B2C_KERNEL_URL: https://gitlab.freedesktop.org/gfx-ci/boot2container/-/releases/v0.9.12.3/downloads/linux-x86_64
    B2C_MARS_SETUP_TAGS: intelgpu:codename:G33
  tags:
    - $B2C_MARS_SETUP_TAGS

i915-g33:
  extends:
    - .ondracka-g33-test
    - .b2c-deqp-test
  variables:
    DEQP_SUITE: i915g
    PIGLIT_PLATFORM: gbm
