[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
renderer_check = "llvmpipe"
tests_per_group = 5000
fraction = 3

# Do some nir clone/serialize validation, but not on the whole run.
[[deqp]]
deqp = "/deqp-vk/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp-vk/mustpass/vk-main.txt"]
renderer_check = "llvmpipe"
tests_per_group = 5000
fraction = 100
prefix = "nir-stress="
  [deqp.env]
  NIR_DEBUG = "clone,serialize"
